version: '2.1'
orbs:
  win: circleci/windows@5.0
  gh: circleci/github-cli@2.6.2

jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Write VERSION
          shell: bash.exe
          command: echo "${CIRCLE_TAG:-$CIRCLE_SHA1}" > pyspy/VERSION
      - run:
          name: Set VERSION in installer.cfg
          shell: bash.exe
          command: sed -i -e "s/@VERSION@/${CIRCLE_TAG:-$CIRCLE_SHA1}/g" installer.cfg
      - run:
          name: Install NSIS via Chocolatey
          command: choco install nsis -y
      - run:
          name: Build pyperclip
          command: |
            mkdir whl
            pip3 wheel --wheel-dir=whl pyperclip
      - run:
          name: Install pynsist
          command: |
            $env:Path = 'C:\Users\circleci\.pyenv\pyenv-win\bin;C:\Users\circleci\.pyenv\pyenv-win\shims;' + $env:Path
            python --version
            pip3 install pynsist
      - run:
          name: Install PySpy requirements
          command: |
            $tagOrSha1 = if ($env:CIRCLE_TAG) { $env:CIRCLE_TAG } else { $env:CIRCLE_SHA1 }
            pip install -r requirements.txt
      - run:
          name: Package pynsist
          command: |
            pynsist installer.cfg
      - run:
          name: Compress Result
          command: |
            $ProgressPreference = "SilentlyContinue"
            mkdir dist
            $tagOrSha1 = if ($env:CIRCLE_TAG) { $env:CIRCLE_TAG } else { $env:CIRCLE_SHA1 }
            Compress-Archive .\\build\\*.exe .\\dist\\PySpy-$tagOrSha1.zip
            Get-ChildItem -Recurse build
            Get-ChildItem -Recurse dist
      - store_artifacts:
           path: dist
      - persist_to_workspace:
          root: dist
          paths:
            - .
workflows:
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - gh/release:
          pre-steps:
            - attach_workspace:
                at: /tmp/dist
          requires:
            - build
          notes-file: CHANGELOG.md
          tag: << pipeline.git.tag >>
          context:
            - GITHUB_CREDS
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          files:
            /tmp/dist/*.zip
