version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Install Python"
          command: choco install python --version=3.7.9
      - run:
          name: Install Python and Pip Dependencies
          command: |
            python --version
            python -m ensurepip --upgrade
            python -m pip install --upgrade pip
            pip install pathlib2
            pip install -r requirements.txt
            pip3 install pyinstaller==3.5
            pyinstaller __main__.spec
workflows:
  my-workflow:
    jobs:
      - build
