version: '2.1'
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Build PySpy
          command: |
            $env:Path = 'C:\Users\circleci\.pyenv\pyenv-win\bin;C:\Users\circleci\.pyenv\pyenv-win\shims;' + $env:Path
            python --version
            pip install -r requirements.txt
            pip3 install pyinstaller
            pyinstaller __main__.spec
      - store_artifacts:
          path: dist/PySpy.exe
          destination: PySpy.exe
workflows:
  workflow:
    jobs:
      - build
